name: Daily Update  # The name displayed in GitHub UI

on:  # Defines when this workflow will run
  schedule:  # Runs on a schedule
    - cron: '0 8 * * *'  # First schedule = 2-3:00 AM Eastern Time (8:00 UTC)
    - cron: '45 22 * * *'  # Second schedule = 4-5:45 PM Eastern Time (22:45 UTC)
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:  # Contains all the jobs that will run in this workflow
  email-daily-updates:  # A single job named "email-daily-updates"
    runs-on: ubuntu-latest  # The type of runner to use

    steps:  # Sequential steps for this job
      - name: Checkout repository  # Step name
        uses: actions/checkout@v3  # Uses a pre-built action

      - name: Set up Python
        uses: actions/setup-python@v4
        with:  # Parameters for this action
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./daily_update  # Directory to execute in
        run: |  # Commands to run
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily market update script
        working-directory: ./daily_update
        env:  # Environment variables
          VANTAGE_API_KEY: ${{ secrets.VANTAGE_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python daily_market_update.py

      - name: Run daily ticker update script
        working-directory: ./daily_update
        env:  # Environment variables
          VANTAGE_API_KEY: ${{ secrets.VANTAGE_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python daily_ticker_update.py

# Example Second Job to Run on Same Schedule
#  another-script: # New job name
#    runs-on: ubuntu-latest
#    needs: generate-report  # Optional: Makes this job wait for the first one to complete
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#
#      - name: Install dependencies
#        working-directory: ./daily_update
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run another script
#        working-directory: ./another_directory
#        env:
#          SOME_API_KEY: ${{ secrets.SOME_API_KEY }}
#        run: python another_script.py